services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: PetFamily
      POSTGRES_USER: Admin
      POSTGRES_PASSWORD: 100506Ki
    ports: 
      - 5435:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  seq:
    container_name: seq
    image: datalust/seq:latest
    restart: always
    environment:
      ACCEPT_EULA: Y
    ports:
      - 5341:5341
      - 8081:80
volumes:
  postgres-data:
    

#  petfamily.api:
#    image: petfamily.api
#    build:
#      context: .
#      dockerfile: src/PetFamily.API/Dockerfile
